// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://udzyovnxqthipzyeqzyi.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkenlvdm54cXRoaXB6eWVxenlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA3NjkwMTksImV4cCI6MjA0NjM0NTAxOX0.Vsaodoga-UFT9g42iZQYPMF8WfF1g4a5PS0w3EA9eD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);